[project]
name = "py-torrent"
version = "0.1.0"
description = "A simple BitTorrent Client"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "libtorrent>=2.0.11",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "requests>=2.32.4",
]
